"use client";
import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { publicApi, type Digest } from "@/lib/api";

export default function SharedDigestPage() {
  const { token } = useParams<{ token: string }>();
  const [digest, setDigest] = useState<Digest | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    publicApi.getSharedDigest(token)
      .then(setDigest)
      .catch(() => setNotFound(true))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-muted-foreground">
        Loading...
      </div>
    );
  }

  if (notFound || !digest) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-3 text-center px-4">
        <p className="text-2xl font-bold">Link not found</p>
        <p className="text-muted-foreground text-sm">This share link may have been revoked or never existed.</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-10">
        {/* Header */}
        <div className="mb-6 border-b border-border pb-4">
          <p className="text-xs text-muted-foreground mb-1">Info Platform · Shared digest</p>
          <h1 className="text-xl font-bold">
            {digest.keywords_used && digest.keywords_used.length > 0
              ? digest.keywords_used.join(", ")
              : digest.title || "Digest"}
          </h1>
          <div className="mt-2 text-xs text-muted-foreground flex flex-wrap gap-3">
            <span>{new Date(digest.created_at).toLocaleString("en-US")}</span>
            <span>{digest.sources_count} sources</span>
            {digest.llm_model && <span>Model: {digest.llm_model}</span>}
          </div>
        </div>

        {digest.keywords_used && digest.keywords_used.length > 0 && (
          <div className="mb-4 flex flex-wrap gap-1.5">
            {digest.keywords_used.map((kw) => (
              <span key={kw} className="px-2 py-0.5 text-xs bg-primary/10 text-primary rounded-full">
                {kw}
              </span>
            ))}
          </div>
        )}

        {/* Content */}
        <div className="bg-background border border-border rounded-lg p-6">
          {digest.summary_md ? (
            <div className="prose prose-slate dark:prose-invert max-w-none prose-h1:text-2xl prose-h2:text-lg prose-h2:border-b prose-h2:border-border prose-h2:pb-1 prose-h3:text-base prose-h3:font-semibold prose-li:my-0.5">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {digest.summary_md}
              </ReactMarkdown>
            </div>
          ) : (
            <div className="text-center py-12 text-muted-foreground">No content</div>
          )}
        </div>

        <p className="mt-6 text-center text-xs text-muted-foreground">
          Generated by Info Platform
        </p>
      </div>
    </div>
  );
}
